sudo: required
language: node_js
node_js:
  - "8"
services: 
  - docker

before_install:
  - docker build -t calebadegbite/docker-react -f Dockerfile.dev .

scripts:
  - docker run calebadegbite/docker-react npm run test -- --coverage